# Generated by Django 3.1 on 2020-09-28 08:46

from django.db import migrations
import django_extensions.db.fields.json


class Migration(migrations.Migration):

    dependencies = [
        ("manager", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="credentialdefinition",
            name="credential_json",
            field=django_extensions.db.fields.json.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="schema",
            name="schema_json",
            field=django_extensions.db.fields.json.JSONField(default=dict),
        ),
    ]
