# Generated by Django 3.1 on 2020-10-06 06:15

import os

from django.db import migrations
from post_office.models import EmailTemplate


def init_email_templates(apps, schema_editor):
    templates_folder = os.path.join("manager", "templates", "emails")
    templates = [
        {"id": "invitation", "subject": "UN Digital ID Credential Issuance",},
    ]

    for template in templates:
        template_file = open(f"{templates_folder}/{template['id']}.html", "r")
        EmailTemplate.objects.create(
            name=template["id"],
            subject=template["subject"],
            content="",
            html_content=template_file.read(),
        )


class Migration(migrations.Migration):

    dependencies = [
        ("post_office", "__latest__"),
        ("manager", "0004_auto_20200930_1510"),
    ]

    operations = [migrations.RunPython(init_email_templates)]
