# Generated by Django 3.1 on 2020-11-05 09:07

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("manager", "0005_email_templates"),
    ]

    operations = [
        migrations.AlterField(
            model_name="connectioninvitation",
            name="connection_id",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="credentialdefinition",
            name="credential_id",
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="credentialoffer",
            name="connection_id",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="credentialoffer",
            name="credential_request",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="credential_offers",
                to="manager.credentialrequest",
            ),
        ),
        migrations.AlterField(
            model_name="credentialrequest",
            name="code",
            field=models.CharField(default=uuid.uuid4, max_length=36, unique=True),
        ),
        migrations.AlterField(
            model_name="schema",
            name="schema_id",
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
