# Generated by Django 3.1 on 2020-11-10 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("manager", "0007_auto_20201110_1622"),
    ]

    operations = [
        migrations.AlterField(
            model_name="credentialdefinition",
            name="schema",
            field=models.ForeignKey(
                limit_choices_to={"schema_id__isnull": False},
                on_delete=django.db.models.deletion.CASCADE,
                to="manager.schema",
            ),
        ),
    ]
