# Generated by Django 3.1 on 2020-11-10 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("manager", "0008_auto_20201110_1725"),
    ]

    operations = [
        migrations.AlterField(
            model_name="credentialrequest",
            name="credential_definition",
            field=models.ForeignKey(
                limit_choices_to={"credential_id__isnull": False},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="credential_requests",
                to="manager.credentialdefinition",
            ),
        ),
    ]
