# Generated by Django 3.1 on 2020-11-10 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manager", "0009_auto_20201110_1728"),
    ]

    operations = [
        migrations.AlterField(
            model_name="credentialdefinition",
            name="name",
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
