# Generated by Django 3.1 on 2021-03-15 13:52

import os

from django.db import migrations

from post_office.models import EmailTemplate


def load_email_template(apps, schema_editor):
    templates_folder = os.path.join("manager", "templates", "emails")
    templates = [
        {"id": "invitation", "subject": "UN Digital ID Credential Issuance"},
    ]

    for template in templates:
        with open(f"{templates_folder}/{template['id']}.html", "r") as template_file:
            EmailTemplate.objects.update_or_create(
                name=template["id"],
                subject=template["subject"],
                content="",
                html_content=template_file.read(),
            )


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0010_auto_20201110_1756'),
    ]

    operations = [
        migrations.RunPython(load_email_template)
    ]
