# Generated by Django 3.1 on 2021-03-12 16:00

from django.db import migrations


def init_organizations(apps, schema_editor):
    organization_names = ["ICC", "HCR", "WFP"]
    Organization = apps.get_model('manager', 'Organization')

    for name in organization_names:
        Organization.objects.create(name=name)


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0011_auto_20210312_1555'),
    ]

    operations = [
        migrations.RunPython(init_organizations, reverse_code=migrations.RunPython.noop)
    ]
