# Generated by Django 3.1 on 2021-03-25 10:49

import os
import structlog as logging

from django.db import migrations

from post_office.models import EmailTemplate

logger = logging.getLogger(__name__)


def load_email_template(apps, schema_editor):
    templates_folder = os.path.join("manager", "templates", "emails")
    template = {
        "id": "invitation",
        "subject": "UN Digital ID Credential Issuance - {{ credential_name }}"
    }

    with open(f"{templates_folder}/{template['id']}.html", "r") as template_file:
        try:
            invitation_template = EmailTemplate.objects.get(name=template["id"])
        except (EmailTemplate.DoesNotExist, EmailTemplate.MultipleObjectsReturned):
            logger.error(f'Error trying to get the template "{template["id"]}" in migration {__file__}')
            return
        invitation_template.subject = template["subject"]
        invitation_template.html_content = template_file.read()
        invitation_template.save()


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0012_auto_20210312_1600'),
    ]

    operations = [
        migrations.RunPython(load_email_template)
    ]
