# Generated by Django 3.2.14 on 2022-07-13 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0014_schema_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='credentialdefinition',
            name='revocation_registry_size',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='credentialoffer',
            name='cred_rev_id',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='credentialoffer',
            name='rev_reg_id',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='credentialrequest',
            name='revoked_credential',
            field=models.BooleanField(default=False),
        ),
    ]
