# Generated by Django 3.2.14 on 2022-08-11 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0016_add_cred_ex_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='credentialoffer',
            name='revocation_id',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
