# Generated by Django 3.2.19 on 2023-06-29 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0019_alter_connectioninvitation_credential_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connectioninvitation',
            name='connection_id',
            field=models.CharField(max_length=100),
        ),
    ]
